
  # Главный compose объединяет все окружения
  # Запускает общую сеть, чтобы контейнеры видели друг друга

  include:
    - docker-compose.backend.yml
    # - docker-compose.frontend.yml
    - docker-compose.ollama.yml
    - docker-compose.base.yml
    - docker-compose.ai.yml

  networks:
    monitoring_net:
    searxng:
