networks:
  monitoring_net:
    external: true

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai_gift_assistant_frontend
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    networks:
      - monitoring_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FRONTEND_PORT}/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai_gift_assistant_backend
    ports:
      - "${BACKEND_PORT}:13000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - monitoring_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT}/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  db:
    image: postgres:16
    container_name: ai_gift_assistant_db
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 5s
      retries: 3
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ai_gift_assistant_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - monitoring_net
        


  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    entrypoint: >
      sh -c "
        ollama serve & 
        until ollama list >/dev/null 2>&1; do
          echo 'Waiting for Ollama to start...'
          sleep 2
        done &&
        ollama pull llama3.1 &&
        wait
      "

  redis:
    image: redis:latest
    container_name: ai_gift_assistant_redis
    ports:
      - "${REDIS_PORT}:6378"
    volumes:
      - redis_data:/data
      - ./redis_users.acl:/usr/local/etc/redis/users.acl:ro
    networks:
      - monitoring_net
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6378", "--appendonly", "yes", "--aclfile", "/usr/local/etc/redis/users.acl"]
    restart: unless-stopped

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis_exporter
    environment:
      - REDIS_ADDR=redis:6378
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "${REDIS_EXPORTER_PORT}:9121"
    networks:
      - monitoring_net
    depends_on:
      - redis
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    networks:
      - monitoring_net
    restart: unless-stopped

volumes:
  postgres_data:
  ollama_data:
  redis_data:
  pgadmin_data:
  redisinsight_data: