

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai_gift_assistant_backend
    ports:
      - "13000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - monitoring_net

  db:
    image: postgres:16
    container_name: ai_gift_assistant_db
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - monitoring_net


  redis-2:
    image: redis:latest
    container_name: ai_gift_assistant_redis
    ports:
      - "6378:6378"
    volumes:
      - redis_data:/data
      - ./backend/redis_users.acl:/usr/local/etc/redis/users.acl:ro
    networks:
      - monitoring_net
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6378", "--appendonly", "yes", "--aclfile", "/usr/local/etc/redis/users.acl"]
    restart: unless-stopped


volumes:
  postgres_data:
  redis_data:

