services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai_gift_assistant_frontend
    ports:
      - "5986:80"
    env_file:
      - .env
    networks:
      - monitoring_net
    restart: unless-stopped

