server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Логи backend
  - job_name: docker-backend
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: "ai_gift_assistant_backend"
        target_label: service

  # Логи frontend
  - job_name: docker-frontend
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: "ai_gift_assistant_frontend"
        target_label: service

  # Логи PostgreSQL
  - job_name: docker-db
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: "ai_gift_assistant_db"
        target_label: service
