networks:
  monitoring_net:
    external: true      
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ${PROMETHEUS_CONFIG_PATH}:/etc/prometheus/prometheus.yml
      - ${PROMETHEUS_RULES_PATH}:/etc/prometheus/rules.yml
    ports:
      - "${PROMETHEUS_PORT}:9090"
    networks:
      - monitoring_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
    ports:
      - "${GRAFANA_PORT}:3000"
    depends_on:
      - prometheus
      - loki
    networks:
      - monitoring_net

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "${LOKI_PORT}:3100"
    volumes:
      - ${LOKI_CONFIG_PATH}:/etc/loki/local-config.yaml
      - ${LOKI_DATA_PATH}:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring_net

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PROMTAIL_CONFIG_PATH}:/etc/promtail/config.yaml
    networks:
      - monitoring_net

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ${ALERTMANAGER_CONFIG_PATH}:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--log.level=debug'
    env_file:
      - .env
    ports:
      - "${ALERTMANAGER_PORT}:9093"
    networks:
      - monitoring_net