global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:13000']

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:5173']

  - job_name: 'db'
    static_configs:
      - targets: ['db:5432']
    metrics_path: /metrics  

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']  

rule_files:
  - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']