groups:
  - name: service-alerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} недоступен"
          description: "{{ $labels.job }} не отвечает более 1 минуты"

      - alert: HighCPUUsage
        expr: rate(node_cpu_seconds_total{mode!="idle"}[2m]) > 0.85
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Высокая загрузка CPU"
          description: "CPU на {{ $labels.instance }} превышает 85% уже 2 минуты"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Высокое использование памяти"
          description: "RAM > 90% на {{ $labels.instance }}"
