groups:
  - name: one-time-alert
    rules:
      - alert: TestOnce
        expr: vector(1)      # всегда 1, чтобы alert сработал
        for: 5s              # ждать 5 секунд перед срабатыванием
        labels:
          severity: critical
          alert_once: "true" # можно использовать для фильтрации
        annotations:
          summary: "Тестовый alert один раз"
          description: "Alert должен сработать только один раз"
  - name: service-alerts
    rules:
      - alert: BackendDown
        expr: up{job="backend"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Backend сервис не отвечает"
          description: "Сервис backend недоступен более 1 минуты"

      - alert: FrontendDown
        expr: up{job="frontend"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Frontend сервис не отвечает"
          description: "Сервис frontend недоступен более 1 минуты"

      - alert: DBDown
        expr: up{job="db"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Postgres недоступен"
          description: "Postgres контейнер не отвечает более 1 минуты"

      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis недоступен"
          description: "Redis контейнер не отвечает более 1 минуты"