name: check
on: 
  push:
    branches: [mlops]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print test message
        run: echo "✅ GitHub Actions is running successfully!"

      - name: List files in repo
        run: ls -la

      - name: Show Docker version
        run: docker --version